---
name: End to End

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

permissions: {}

jobs:
  images:
    name: Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Build the images if necessary
        uses: submariner-io/shipyard/gh-actions/cache-images@devel
  e2e-full:
    name: E2E
    needs: images
    if: contains(github.event.pull_request.labels.*.name, 'ready-to-test')
    timeout-minutes: 45
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cable-driver: ['wireguard']
        extra-toggles: ['']
        globalnet: ['']
        # Run most tests against the latest K8s version
        k8s_version: ['1.30']
        exclude:
          - cable-driver: wireguard
            extra-toggles: ovn
    steps:
      - name: Check out the repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Run E2E deployment and tests
        uses: submariner-io/shipyard/gh-actions/e2e@devel
        with:
          using: ${{ matrix.globalnet }} ${{ matrix.cable-driver }} ${{ matrix.extra-toggles }}

      - name: Post mortem
        if: always()
        uses: submariner-io/shipyard/gh-actions/post-mortem@devel
